FROM arm64v8/golang:1.17-alpine@sha256:84987494849496d5724d5dbd020a74ab9224406717a7c6e2027c44d4a552c2c5

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Go" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Go" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/golang.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/golang" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/golang"

RUN apk add bash make git curl gcc musl-dev libc-dev binutils-gold ncurses
