FROM amd64/golang:1.17-alpine@sha256:af5414ba2ef2fe732dc83bbc163060ab2eca75d994a97f0a15749b062996f706

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Go" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Go" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/golang.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/golang" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/golang"

RUN apk add bash make git curl gcc musl-dev libc-dev binutils-gold ncurses
