FROM arm64v8/golang:1.16-alpine@sha256:b544ac55ad1f9997f4436b70fdfcdef8bdc144837401f392ed1eb3393f99baa6

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Go" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Go" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/golang.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/golang" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/golang"

RUN apk add bash make git curl gcc musl-dev libc-dev binutils-gold ncurses
