FROM arm32v7/golang:1.19-alpine@sha256:27da10d6df5c8221cad2cf9232698a19723cdc611f7d55f9e0ffe7addb794c9e

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Go" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Go" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/golang.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/golang" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/golang"

ARG RETRY_VERSION

# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"

RUN apk add bash make git curl gcc musl-dev libc-dev binutils-gold ncurses && \
  curl -SsfL -o /usr/local/bin/retry "https://github.com/owncloud-ci/retry/releases/download/v${RETRY_VERSION##v}/retry" && \
  chmod 755 /usr/local/bin/retry
