FROM arm64v8/golang:1.19-alpine@sha256:d651d550bf8db22201c8dffd4e9ace500ec068111a3cf3ee52233c0479e3bdbc

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Go" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Go" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/golang.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/golang" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/golang"

ARG RETRY_VERSION

# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"

RUN apk add bash make git curl gcc musl-dev libc-dev binutils-gold ncurses && \
  curl -SsfL -o /usr/local/bin/retry "https://github.com/owncloud-ci/retry/releases/download/v${RETRY_VERSION##v}/retry" && \
  chmod 755 /usr/local/bin/retry
